# Keep all Fabric/Minecraft entry points
-keep @net.fabricmc.api.Environment class *
-keep class net.matrix.Matrix { *; }

# Keep Mixins entirely and don't obfuscate them
-keep class net.matrix.mixin.** { *; }

# Keep the GUI, Utils and Config classes
-keep class net.matrix.gui.** { *; }
# AuthManager is now obfuscated automatically
# -keep class net.matrix.systems.auth.AuthManager { *; }
-keep class net.matrix.utils.** { *; }
-keep class net.matrix.systems.config.** { *; }

# Keep all classes in the modules package
-keep class net.matrix.systems.modules.** { *; }

# General Obfuscation
-repackageclasses ''
-allowaccessmodification
-overloadaggressively
-keepattributes Signature,Exceptions,AnnotationDefault

# Rename everything else in our package
-obfuscationdictionary dictionary.txt
-classobfuscationdictionary dictionary.txt
-packageobfuscationdictionary dictionary.txt

# Library handling
-dontwarn **
-dontnote **

# Keep synthetic for Java 21 compatibility
-keepattributes *Annotation*,InnerClasses,Signature,EnclosingMethod
